### ISSUE TITLE
[WIKI] {Mega Issue} Ensure Project Structure meets Project Standard

### ISSUE THREAD

**Issue by Alxjlv** [we-are-number-1/yumble#101]
- [x] Repo should have:
    - [x] Brief project description
    - [x] License
    - [x] README
    - [x] Contributing
    - [x] Code of Conduct
    - [x] wiki
    - [x] Initial list of tasks
- [x] Wiki should include:
    - [x] List of contributors (student mapped to username)
    - [x] List of contributions made
    - [x] Minutes from meetings
- [x] Initial list of tasks should be setup as issues, and labels should be decided on
- [x] Labels should be described in project documentation
- [x] Types of contributions:
    - [x] Code + documentation 
        - [x] should have an associated issue and be reviewed
        - [x] all of these should have associated tests & be run by an automated test suite
    - [x] Reviews
        - [x] Squash on merge
        - [x] Test suite must be run
        - [x] Test suite must exist
        - [x] Reviews must be acquired
    - [x] Creating new issues
        - [x] Bugs
        - [x] Feature Requests
    - [x] Approval process for issues
        - [x] Documented issue approval process
        - [x] This could be as simple as dragging the card or leaving a comment
- [x] Enforce Workflow:
    - [x] Fork and clone main repo
    - [x] New feature branch on fork for each issue
    - [x] Consider feature flagging for big issues
    - [x] Rebase often in your local clone
    - [x] Create PRs and link issues to close
    - [x] Pull from upstream main
    - [x] Document merging rules
    - [x] Assign people to issues
        - [x] One claimed issue at a time
    - [x] Need to identify dependencies between tickets
- [x] All team members need one code contribution PR and one code review

**Comment by blakehattingh** [comment]
nice work, approved.
