### ISSUE TITLE
[BUG] Modify createSession & createPreferences on backend

### ISSUE THREAD

**Issue by BlinkCreator** [we-are-number-1/yumble#141]
1. Go to https://yumble.xyz
2. Click on create game
3. Inspect mongoDB and view Session object
4. See that Session contains no body or session code. 
5. Session needs to have a useful body sent to the payload and both api are called at the same time.  Only one api needs to be called after create game is hit and session should look like this straight afterwards.
{
  "_id": "123hiy1y781e2y7",
  "isFinished": false,
  "preferences": {
    "location": "",
    "distance": 0,
    "cuisines": [],
    "price": []
  },
  "results": {
    "restaurants": []
  }
}

Additional context:
API contracts need to be upheld especially when checking if PR's meet the same functionality as detailed in their api contracts. API in the future need to be designed with robustness, scalability and future modifiability in mind for any future potential updates for this project.

**Comment by Alxjlv** [comment]
Seems like a valid issue 👍
