### ISSUE TITLE
[FEAT] Add socket and database persistence 

### ISSUE THREAD

**Issue by David-Xia0** [we-are-number-1/yumble#169]
Connect socket user information and mongo DB user information / session

---

Updated information after investigation (Team 4):

The aim is to allow users to re-enter past lobby ids and re-retrieve their Yumble results.
These child issues need to be resolved before this issue can be done.
- [x] https://github.com/we-are-number-1/yumble/issues/278
- [x] https://github.com/we-are-number-1/yumble/issues/275
- [x] https://github.com/we-are-number-1/yumble/issues/274
- [x] https://github.com/we-are-number-1/yumble/issues/272
- [x] https://github.com/we-are-number-1/yumble/issues/296

**Comment by parfei** [comment]
Completed with  #278,  #275, #274, #272, #296
