### ISSUE TITLE
[BUG] Share link for joining the room is now redundant because of MemoryRouter changes

### ISSUE THREAD

**Issue by Alxjlv** [we-are-number-1/yumble#205]
### To Reproduce the bug:

1. Go to 'yumble.xyz'
2. Click on 'Create Room'
3. Enter a random location
4. Click 'go'
5. Click 'share'
6. Click on the share link

Screenshot:
![Screenshot 2021-03-21 134419](https://user-images.githubusercontent.com/44216323/111890127-8e544600-8a4b-11eb-9ec6-42798f5c913f.png)

* OS: Windows
* Browser: Chrome

**Comment by David-Xia0** [comment]
Approved, in call

**Comment by Alxjlv** [comment]
Copy to clipboard could be a good addition if we're just adding the code instead

**Comment by DavidHuangz** [comment]
I changed the share link like two days ago. So it just says share the code and link to your friend for them to copy and paste.
