### ISSUE TITLE
[FEAT] Change result screen when there are more than one restaurant get the highest votes  

### ISSUE THREAD

**Issue by zxia545** [we-are-number-1/yumble#265]
## To allocate the place of this issue:

The current result screen only shows one restaurant when there is more than one restaurant with the highest votes. This may need to change, the other restaurants with the same amount of votes need to show up as well.
Screenshot:
![image](https://user-images.githubusercontent.com/49884519/113795838-64578f00-9780-11eb-907b-2e59fa9a3e96.png)

**Comment by reeved** [comment]
How would we show multiple restaurants? Should we instead just randomly select one of the restaurants and return it?

**Comment by zxia545** [comment]
Not sure about this. We just consider this may need some improvement on it.

**Comment by reeved** [comment]
I think it would make sense to select a random one. This app is trying to choose a restaurant for the users and presenting them with a choice to make at the end might defeat that purpose right? 😄

**Comment by reeved** [comment]
This has been indirectly solved by #330. Feel free to re-open this issue if anyone in the future feels like there is a better solution to displaying multiple top restaurants.
