### ISSUE TITLE
[BUG] Completed Sessions Never Removed

### ISSUE THREAD

**Issue by UltimaKuma** [we-are-number-1/yumble#275]
***
#### Describe the bug:
When a session is completed ie a game of yumble is completed, it is possible to still join the room. This is because the game is never removed from the activeGames map in `Games.js`

This is a potential memory leak that could cause the server to crash if not dealt with.

### To Reproduce the bug:
1. Finish a game of yumble
2. Create a new tab and rejoin the same game with the same code
The expected behaviour is that the lobby code should be invalid OR should take you to the results screen of the completed game

Screenshots - 
![image](https://user-images.githubusercontent.com/49135923/113952103-21bdb180-9869-11eb-95e4-b9d6b7c6d6e8.png)
Here you can see a room that has been joined without the host, as the room has been joined after the game has been completed.

**Comment by parfei** [comment]
Merged in fix PR
