### ISSUE TITLE
[FEAT] Add expiry to MongoDB documents

### ISSUE THREAD

**Issue by parfei** [we-are-number-1/yumble#278]
[FEAT] Add expiry to MongoDB documents
*Dsc: Modify existing code that deals with the MongoDB persisting, and ensure there is an expiry set for them.
Also make sure to tell the user that the data disappears after the set expired -- **in the backend** or document this in the wiki: https://github.com/we-are-number-1/yumble/wiki/Yumble-Architecture-&-Design

The expiry is to ensure that we do not run out of lobbyids to assign to rooms, as we _persist_ lobby's results even after when a game has finished. This will also clean the database out of old, most likely unused data after a week or so (+ security benefits)!

**Comment by skyn310198** [comment]
Issue has been approved !

**Comment by parfei** [comment]
We have added documentation to the wiki: https://github.com/we-are-number-1/yumble/wiki/Yumble-Architecture-&-Design#database---mongodb

**Comment by parfei** [comment]
Merged in PR
