### ISSUE TITLE
[FEAT] Remove unused code related to cusine field of restaurant card

### ISSUE THREAD

**Issue by tguernier** [we-are-number-1/yumble#286]
## Issue Description
There is a 'cuisine' field in the restaurant card, but this is always a hard-coded value as the API call to get the cuisine has not been implemented (the Google Maps API does not provide cuisine info). Implementing this feature would require implementing this API call and UI elements to select the cuisines the players want, which would be too much work. Removing the unused code associated with this field would clean up the code and make it easier to understand.

# List of tasks
- Remove unused code relating to the cuisine field
- Remove UI elements referring to the cuisine field
- Change tests to reflect code changes

**Comment by ateagit** [comment]
Good issue, Approved. Please assign youself though.
