### ISSUE TITLE
[FEAT] Add swiping functionality for cards in SwipingPage

### ISSUE THREAD

**Issue by ateagit** [we-are-number-1/yumble#287]
## Issue Description
Add a way for cards to swiped left or right corresponding to Keen or Nope. 
The cards should retain its existing look and feel and be able to be swiped on both phone/desktop alike.

## Issue Tasks
- [x] Add package for gestures
- [x] Add package for animations
- [x] Connect and implement functionality.

**Comment by tguernier** [comment]
Approved
