### ISSUE TITLE
[BUG] Sessions are removed from mongoDB far earlier than expiry

### ISSUE THREAD

**Issue by Dhors** [we-are-number-1/yumble#296]
## Bug Report Body:
Currently, new sessions created for each game are being removed before the game ends. The sessions are expected to be removed on expiry after 7 days.
By removing the sessions from the database faster than the game itself, it causing the error of where the code is trying to find a non-existent session to work with. This was because the sessionID was no longer associated with a session (as it is removed)

Process to find the issue:

We have located the source of the issue to:
createdAt: {type: Date, expires: config, default: Date.now},

One small note is that `expires: config` should be changed to `expires: config.session_expiry`. However this does not solve the issue. 
Firstly, the `expires: config.session_expiry` part was entirely removed. However, it still deletes the sessions from the database.

Then the entire line was removed `createdAt: {type: Date, expires: config, default: Date.now}`,
This stopped removing the sessions from the database and the null session error stop occurring.

### To Reproduce the bug:
Note: this bug does not always present itself visibly. And so the mongoDB sessions log must be looked at.

1. Run the Yumble game, until the result screen.
2. Keep track of the session created on the mongoDB sessions log.
3. The sessions should at some point be removed.
4. Click on the see results button.
5. The pie chart will be missing.
6. Expected behaviour: The pie chart should not be missing, and the session should not be removed from MongoDB.

Screenshots - 
Error of the session that could not be found being used.
![image](https://user-images.githubusercontent.com/45830988/114295325-ae31d380-9af8-11eb-8fa6-da9a52e68a15.png)

MongoDB missing the session.
![image](https://user-images.githubusercontent.com/45830988/114295419-3fa14580-9af9-11eb-9482-b39322e37b6a.png)

* OS: Windows
* Browser: chrome and Edge

**Comment by parfei** [comment]
This may be very relevant: https://stackoverflow.com/questions/29525010/mongoose-expires-property-not-working-properly

**Comment by parfei** [comment]
Merged in PR that fixes it
