### ISSUE TITLE
[FEAT] Modify the styling for frontend components

### ISSUE THREAD

**Issue by SreenikethRaghavan** [we-are-number-1/yumble#298]
## Feature Description: 
- Modify the styling of the frontend components so that the app has a dark theme and a cleaner aesthetic
- Remove the Comic sans fonts and the cartoon aesthetic
- Make use of Bootstrap components for layout and styling

The changes will be made in frontend/components

## Blocked by:
#17

**Comment by Dhors** [comment]
Nice issue Sree!
 
We should aim to remove a lot of the rounding of components from the original Yumble.
We should also try to limit the colours of our buttons to a few select colours so that users, can develop a general feel/intuition for what the buttons do.

**Comment by reeved** [comment]
Closed as the frontend has now completed its revamp. There are minor tweaks outstanding but they have their own issues created.
