### ISSUE TITLE
[BUG] Background Image is Low-Res 

### ISSUE THREAD

**Issue by reeved** [we-are-number-1/yumble#311]
#### Describe the bug:
The current background image is very low res and doesn't look good. We should replace it with a much higher-res version 

### To Reproduce the bug:
A clear description of the steps to reproduce the behaviour:

1. Just open the app
2. Look at all the pixels

### Additional context:
High Res version: https://whitecoconutthai.com/wp-content/uploads/2020/02/AdobeStock_297677001-scaled.jpeg

**Comment by SreenikethRaghavan** [comment]
Work completed in PR #320
