### ISSUE TITLE
[BUG] No error message when Restaurants can't be found

### ISSUE THREAD

**Issue by reeved** [we-are-number-1/yumble#314]
#### Describe the bug:
At the moment, if the app can't find any restaurants that match your preference, you won't find out. Instead, you will just keep clicking the "Go" button with no response at all. 

### To Reproduce the bug:
A clear description of the steps to reproduce the behaviour:

1. Create a lobby
2. Enter 'Lake Taupo, Waikato, New Zealand' as the location
3. Leave every other parameter as default
4. Click the "Go" button
5. Observe absolutely nothing

Ideally, there would be an error message of some sort that would let you know to update your preferences in order to widen the search parameters.

### What it should look like:
![image](https://user-images.githubusercontent.com/7234148/115023537-0ca0ec80-9f13-11eb-8ab2-5f45403af50e.png)

### Additional context:
In `Common/LocationHelper.js`, the `getNearbyRestaurants` method returns a promise that is expected to be information about the restaurant cards. When there are no restaurants found, this is does not get resolved. This is because `status !== OK`. Instead, `status === ZERO_RESULTS`. In `3.Preferences/Preferences.js`, you can add a condition in the `handleSearch` method that checks if `data === 'ZERO_RESULTS'` and if so, add a warning message somewhere. This message should be hidden again once search parameters get changed.

A way of going about this would be to create another `useState` for `showErrorMessage` which when true, shows the message, and when false, hides it. This would get set to false everytime a parameter gets changed.

Make sure to use the CSS Property `visibility: visible | hidden` for the error message to prevent UI elements from shifting.

**Comment by Dhors** [comment]
Nicely documented issue Reeve!
This makes it super easy to work on, thank you.
