### ISSUE TITLE
[FEAT] Modify the Go Button styling on the Join Page and the Close button styling

### ISSUE THREAD

**Issue by SreenikethRaghavan** [we-are-number-1/yumble#321]
## Description:
- Modify the colour of the Go Button on the Join page to be orange with a yellow hover on effect
- Change the Close button text in the help popup from 'close!' to 'Close' 

## Affected files: 
- Changes will be made mainly in App.css, JoinGroup.js and MapModal.js

**Comment by Dhors** [comment]
Nice change  Sree.

it will make the go button and close button more consistent with other buttons used throughout Yumble.
